AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ProjectId:
    Type: String
    Description: Authentication Service API

Resources:

#  AuthServiceDynamoDBPermissions:
#    Type: AWS::IAM::Policy
#    Properties:
#      PolicyName: "AuthServiceDynamoDBPermissions"
#      PolicyDocument:
#        Version: "2012-10-17"
#        Statement:
#        - Effect: "Allow"
#          Action:
#          - "dynamodb:*"
#          Resource: "arn:aws:dynamodb:*:*:table/UsersDynamoDBTable*"
##          Resource: "*"
##          Resource: "arn:aws:dynamodb:eu-west-1:180742419520:table/"!Ref UsersDynamoDBTable "/index/*"

  # Users Table
  UsersDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: userID
        AttributeType: S
      - AttributeName: userEmail
        AttributeType: S
      KeySchema:
      - AttributeName: userID
        KeyType: HASH
      GlobalSecondaryIndexes:
      - IndexName: "userEmail-index"
        KeySchema:
        - AttributeName: "userEmail"
          KeyType: "HASH"
        Projection:
          ProjectionType: "ALL"
        ProvisionedThroughput:
          ReadCapacityUnits: "2"
          WriteCapacityUnits: "1"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  # Users Events Table
  UsersEventDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: eventID
        AttributeType: S
      - AttributeName: eventType
        AttributeType: S
      - AttributeName: userID
        AttributeType: S
      KeySchema:
      - AttributeName: eventID
        KeyType: HASH
      - AttributeName: userID
        KeyType: RANGE
      GlobalSecondaryIndexes:
      - IndexName: "userID-eventType-index"
        KeySchema:
        - AttributeName: "userID"
          KeyType: "HASH"
        - AttributeName: "eventType"
          KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"
        ProvisionedThroughput:
          ReadCapacityUnits: "2"
          WriteCapacityUnits: "1"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2


  AuthenticationServiceAPI:
    Type: AWS::Serverless::Function
    StageName: v0
    Properties:
      Handler: bin/lambdaRunner.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Environment:
        Variables:
          NODE_ENV: prod
          AUTH_JWT_SECRET: green_eggs_and_ham
          USERSTABLE: !Ref UsersDynamoDBTable
          USERSEVENTSTABLE: !Ref UsersEventDynamoDBTable

      Policies:
      # Give just CRUD permissions
      - DynamoDBCrudPolicy:
          TableName: !Ref UsersDynamoDBTable
      - DynamoDBCrudPolicy:
          TableName: !Ref UsersEventDynamoDBTable

      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /{all+}
            Method: any
        GetEventAtRoot:
          Type: Api
          Properties:
            Path: /
            Method: any
      ReservedConcurrentExecutions: 5